# Generated by Django 3.0.7 on 2020-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='confidence',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
