# Generated by Django 3.0.7 on 2020-06-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuator', '0002_tshirt_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='saved_at',
            field=models.DateTimeField(),
        ),
    ]
